Opened-Developers/open-mind

- package-lock.json
- package.json
- tailwind.config.js
resolved: #4
tailwindcss 패키지와 설정파일을 삭제했습니다.
> [#4] tailwindcss 패키지 삭제

- package-lock.json
- package.json
- src/api/axios.js
resolved: #34 
- axios 패키지 설치
- 인스턴스 파일 생성 (import 해서 사용)
- [axios 사용법](https://www.codeit.kr/tutorials/47/Axios-%EC%82%AC%EC%9A%A9%EB%B2%95)
> [#34] axios 인스턴스로 baseURL 설정

- package.json
- src/App.jsx
resolved: #39
react-router-dom 설치 및 React Route 설정
> [#39] React Route 설정

- src/components/Buttons.jsx
- src/components/Buttons.module.css
- src/stories/Buttons.stories.jsx
- src/styles/global.css
> [#52] 플로팅 버튼 추가

- src/api/getFeedListAll.js
- src/pages/MainPage/MainPage.jsx
- src/pages/MainPage/MainPage.module.css
resolved: #17
공통 컴포넌트 적용
디자인 일부 수정
멘토링 피드백 반영
> [#17] 메인 페이지 수정 작업

- src/components/Reaction.jsx
- src/components/Reaction.module.css
- src/stories/Reaction.stories.jsx
resolved: #72 
좋아요 싫어요 버튼 구현
개별 버튼에 onClick핸들러를 각각 넣어줍니다.
> [#72] 좋아요 싫어요 버튼 구현

- src/api/createQuestion.js
- src/api/getFeedList.js
- src/api/getFeedListAll.js
- src/api/getFeedQuestions.js
- src/api/getProfileById.js
- src/api/openMindAxios.js
- src/api/postNewAnswer.js
- src/api/postNewFeed.js
- src/api/postQuestionReaction.js
- src/components/Badges.module.css
- src/components/FeedCard.jsx
- src/components/FeedCardAnswer.jsx
- src/components/FeedCardBadge.jsx
- src/components/FeedCardList.jsx
- src/components/FeedCardQuestion.jsx
- src/components/QuestionModal/QuestionModal.jsx
- src/components/QuestionModal/QuestionModal.module.css
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
- src/utils/getRelativeDate.js
> [#27] 질문 작성하기 버튼으로 띄우는 모달 구현

- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #80 
로컬스토리지 판별로 답변/질문 버튼 노출
> [#80] 로컬스토리지 판별로 답변/질문 버튼 노출

- src/components/Dropdown.jsx
- src/components/Dropdown.module.css
- src/stories/Dropdown.stories.jsx
resolved: #77 
메뉴 포지션 absolute로 변경
기타 자잘한 스타일 수정
> [#77] 드롭다운 스타일 수정

- src/api/getFeedQuestions.js
- src/api/postNewFeed.js
- src/components/QuestionModal/QuestionModal.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #30 
무한스크롤 구현
- 두 번째 무한 스크롤부터 호출이 다발하는 버그가 있습니다.
> [#30] 무한스크롤 구현

- src/App.jsx
- src/pages/NotFound/NotFoundPage.jsx
- src/pages/NotFound/NotFoundPage.module.css
- src/styles/global.css
resolved: #85 
404페이지를 추가했습니다.
> [#85] 404 페이지 추가

- OneDrive/바탕 화면/open-mind-feat-18/src/pages/FeedListPage/FeedListPage.jsx
> [#18] 질문 목록 페이지 구현

- OneDrive/바탕 화면/open-mind-feat-18/src/pages/FeedListPage/FeedListPage.jsx
- src/pages/FeedListPage/FeedListPage.jsx
- src/pages/FeedListPage/FeedListPage.module.css
- src/pages/FeedListPage/components/Pagenation.jsx
- src/pages/FeedListPage/components/Pagenation.module.css
- src/pages/FeedListPage/components/UserCard.jsx
- src/pages/FeedListPage/components/UserCard.module.css
> [#18] 질문 목록 페이지 경로 수정

- src/components/FeedCardList.jsx
- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
resolved: #62
답변하기 페이지 질문 안 뜨는 오류 해결
무한 스크롤 추가
> [#62] 답변하기 페이지 질문 안 뜨는 오류 해결, 무한 스크롤 추가

- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #96 
질문 0개 피드 무한요청 해결
실수로 62번 이슈 커밋도 하나 들어갔네요...! 다음에는 상관 없는 커밋은 없애고 PR 하겠습니다!! ㅠㅠ
> [#96] 질문 0개 피드 무한요청 해결

- src/pages/AnswerPage/AnswerPage.module.css
- src/pages/IndividualFeedPage/IndividualFeedPage.module.css
resolved: #107
질문 컨테이너, 질문 카드 가로폭 문제 개별피드&답변하기 페이지 일괄 해결!
> [#107] 질문 컨테이너, 질문 카드 가로폭 문제 개별피드&답변하기 페이지 일괄 해결

- src/components/FeedCard.jsx
- src/components/FeedCardList.jsx
- src/components/QuestionModal/QuestionModal.jsx
- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #96
list 에서 질문이 있는 피드, 없는 피드 무엇에 들어가도
handleLoadQuestions 가 무한 호출되는 현상
> [#96] 무한호출 오류 해결

- src/api/getFeedQuestions.js
- src/pages/AnswerPage/AnswerPageContainer.jsx
resolved: #95
공통 FeedCardList 코드 정리 
공통적으로 사용되는 handleLoadQuestions(질문불러오기), observer(무한스크롤)을 
페이지 아닌 컴포넌트 FeedCardList로 이동시킴
> [#95] 공통 FeedCardList 코드 정리 

- src/components/Buttons.jsx
- src/components/Buttons.module.css
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
- src/styles/global.css
resolved: #114 
플로팅 버튼 답변하기하기 오류 수정
스타일링 일부 수정
> [#114] 플로팅 버튼 오류 수정

- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #132
무한스크롤을 다시 구현하다가 여러 번 호출되는 문제가 있어서 해결했습니다.
현재 dev 기준으로는 아예 무한스크롤이 안 되기 때문에 다른 브랜치 이어서 작업했습니다
> [#132] 무한스크롤 반복호출 오류 해결

- src/components/QuestionModal.jsx
resolved: #112
- 질문 등록하기 버튼 수정 후속 작업 (문구 변경)
- 질문 등록 성공하면 모달 입력창 비우기
- 상위에서 사라진 함수 prop에서 임시로 제거
> [#112] 질문 등록 후 모달 입력창 비우기

- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
> [#125] 파라미터 바뀌면 질문 새로 로드 다중호출 해결

- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #125
사소한 걸 자꾸 빼먹게 되네요..
> [#125] .then 통일

- src/App.jsx
- src/components/FeedCard.jsx
- src/components/FeedCardList.jsx
- src/components/QuestionModal.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #115 
에러 스테이트 정리
context 토스트 적용
질문 등록 300자 제한 에러 추가 
@KWSony 확인 부탁 드립니다 !
> [#115] 에러 스테이트, 토스트 리팩토링

- src/components/FeedCard.module.css
- src/components/FeedCardList.jsx
- src/components/FeedCardList.module.css
> [#129] 질문개수 요약문구 정렬 수정

- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #127 
개별피드, 답변하기 상단 로고에 피드리스트 링크 추가
> [#127] 개별피드, 답변하기 상단 로고에 피드리스트 링크 추가

- src/App.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: {#96}
첫 번째 로딩의 조건문을 따로 두어 무한호출을 해결했습니다.
> [#96] isFirstLoad 추가하여 빈 피드 무한호출 해결

- src/App.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #125
질문 초기로딩의 기준을 프로필로딩으로 하고 isNewProfile 스테이트 추가
> [#125] 다른 피드 들어갔을 때 데이터 바뀌지 않는 문제 해결

- src/pages/FeedListPage/FeedListPage.jsx
> [#149] 로고 클릭으로 메인 이동

- src/components/Dropdown.module.css
resolved: #151
눈에 띄는 버그라서 발표 전에 수정했습니다
> [#151] 드롭다운 배경색 추가

- src/components/Dropdown.module.css
- src/pages/FeedListPage/components/UserCard.module.css
resolved: #153
눈에 띄는 버그라서 수정했습니다.
> [#153] 피드카드 배경색 추가

- src/components/QuestionModal.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #155 
질문 0개 피드에서 질문을 등록하면 질문 목록 업데이트 되지 않는 문제를 해결했습니다
> [#155] 질문등록하면 프로필 다시 불러오도록 수정(질문 0개 피드 리프레시 강제)

- src/App.jsx
- src/components/QuestionModal.jsx
- src/pages/AnswerPage/AnswerPage.jsx
- src/pages/AnswerPage/AnswerPageContainer.jsx
- src/pages/IndividualFeedPage/IndividualFeedPage.jsx
resolved: #157 
에러 토스트 터지는 것 수정했습니다.
AnswerPage 하위컴포넌트 에러메시지는 수정하지 않았습니다.
> [#157] 질문 0개 피드에서 전체삭제 버튼 클릭 시 나는 에러 수정

- src/pages/FeedListPage/FeedListPage.jsx
- src/pages/FeedListPage/components/Pagenation.jsx
> [#159] 페이지네이션 현재 페이지 표시 수정

- src/pages/FeedListPage/FeedListPage.jsx
- src/pages/FeedListPage/FeedListPage.module.css
resolved: #163
질문 목록 페이지 모바일 사이즈 디자인 수정
> [#163] 질문 목록 페이지 모바일 사이즈 디자인 수정

- public/index.html
resolved: #169 
%PUBLIC_URL%/thumbnail.png
형태의 url을 사용했습니다.
> [#169] 공유링크 썸네일 주소에 환경변수 적용
